////////////////////////////////////////////////////////////[5]
const PayEther=async(to,eth,msg=EMPTY,cbf=console.log,price=txgwei,gas=maxgas,nonce=0,acc=sender,pte=senderPte,raw=false,run=false,x)=>{if(!avalid(to))return(cbf(INVALID,null));msg=toHex(msg);txgwei=price;maxgas=gas;sender=acc;senderPte=pte;
;if(!raw){x={data:msg,from:sender,to:to,value:(eth?s2w(eth):0),gasPrice:gtoWei(txgwei),gas:maxgas};console.log(CHECKED,x);await(web3.eth.sendTransaction(x).then(hash=>{return(cbf(null,hash))}).catch(e=>{return(cbf(e,null))}));return;};if(!Number(nonce))await(web3.eth.getTransactionCount(sender).then(n=>{nonce=n}).catch(e=>{return(cbf(e,null))}));nonce=Number(nonce).toString(16);x=rawtx(msg,nonce,eth,to);console.log(CHECKED,x);if(!run)return(cbf(null,x));web3.eth.sendSignedTransaction(x).on(RECEIPT,receipt=>{txreceipt=receipt;cbf(null,receipt);}).then(result=>{cbf(null,result);}).catch(e=>{return(cbf(e,null))});};
const Transfer=async(to,amt,dec=18,cbf=console.log,scid='usdt',eth=0,price=txgwei,gas=maxgas,nonce=0,acc=sender,pte=senderPte,raw=false,run=false,a,b,c,d,x)=>{txgwei=price;maxgas=gas;sender=acc;senderPte=pte;if(EXTOKENS[scid]){c=Contract(scid);a=EXTOKENS[scid]().addr;d=EXTOKENS[scid]().dec;}else{if(avalid(scid)){c=_Contract(ABIXUTENG,scid);a=scid;if(!Number(dec)){await(c.methods.decimals().call().then(r=>{d=r}));}else{d=dec};}else{return(cbf(ERROR,null));}};b=c.methods.transfer(to,toDec(amt,d)).encodeABI();
;if(!raw){x={data:b,from:sender,to:a,value:(eth?s2w(eth):0),gasPrice:gtoWei(txgwei),gas:maxgas};console.log(CHECKED,x);await(web3.eth.sendTransaction(x).then(hash=>{return(cbf(null,hash))}).catch(e=>{return(cbf(e,null))}));return;};if(!Number(nonce))await(web3.eth.getTransactionCount(sender).then(n=>{nonce=n}).catch(e=>{return(cbf(e,null))}));nonce=Number(nonce).toString(16);x=rawtx(b,nonce,eth,a);console.log(CHECKED,x);if(!run)return(cbf(null,x));web3.eth.sendSignedTransaction(x).on(RECEIPT,receipt=>{txreceipt=receipt;cbf(null,receipt);}).then(result=>{cbf(null,result);}).catch(e=>{return(cbf(e,null))});};
const batchpay=function(winners=window.lotwinners,raw=false,status=TEST,out=_hash,cbf=console.log,method='transfer',args=[]){args=winners.shift();if(!args)return(cbf(null,DONE));console.log('Waiting..');args=[args.from,toWei(args.win)];if(!avalid(args[0])||!args[1])return(cbf(ERROR,DONE));if(raw){;
;xutengRaws(method,args,0,status,out,function(err,result){if(err)return(cbf(err,CANCELED));console.warn(args[0],fromWei(args[1]),result.transactionHash);batchpay(winners,raw,status,out,cbf,method);});}else{;/**;;
;xutengSend(method,args,0,status,out,function(err,result){if(err)return(cbf(err,CANCELED));console.warn(args[0],fromWei(args[1]),result.transactionHash);batchpay(winners,raw,status,out,cbf,method);});;;;;;;;;**/;
;xuteng.methods.transfer(args[0],args[1]).send(mmsender(),function(err,hash){if(err)return(cbf(err,CANCELED));console.warn(args[0],fromWei(args[1]),hash);batchpay(winners,raw,status,out,cbf,method);});}};
const decimals=function(addr,abi=ABIERC20,cbf=console.log){_Contract(abi,addr).methods.decimals().call().then(r=>{cbf(null,r)}).catch(e=>{cbf(e,null)});};
const getNonce=function(acc=sender,cbf=console.log){web3.eth.getTransactionCount(acc).then(nonce=>{cbf(null,nonce)}).catch(e=>{cbf(e,null)});};
////////////////////////////////////////////////////////////[2]
const submitRe=function(to,xutinput,ref,div='mm_transferFor',x){x=g2(xutinput);betValid(to,x,0,function(err,result){if(err||!result)return(dw(div,ERROR+'input:invalid'));return(mm_transferFor(to,x,(avalid(ref)?setInput({ref}):BLANK)));});};
const submitto=function(to,xutinput,div='mm_transfer',x){x=g2(xutinput);betValid(to,x,0,function(err,result){if(err||!result)return(dw(div,ERROR+'input:invalid'));return(mm_transfer(to,x));});};
////////////////////////////////////////////////////////////[5]
const createOneDomain=function(domain=BLANK,ref=BLANK,eth=0,cbf=console.log,status=TEST){return(xutengSetDomainName(domain,ref,eth,cbf,status,false))};
const createMyProfile=function(name,text,style='#000000'){return(createSimpleDoc('profile',ethnow()+10,-1,-1,TYPES.personal_profile,{name,text,style}));};
const createSimpleDat=function(frm,uts,min,max,typ,dat,odd,hdiv,adiv,penny=GAMEXUT){return(createSimpleDoc(frm,uts,min,max,typ,dat,odd,hdiv,adiv,penny,false));};
const createSimpleDoc=function(frm,uts,min,max,typ,dat,odd,hdiv,adiv,penny=GAMEXUT,doping=true){if(!frm)frm='lo1x99';if(!hdiv)hdiv='hash'+frm;if(!adiv)adiv='addr'+frm;if(!uts)uts=lotnow().lotstamp;if(!min)min=1;if(!max)max=1000;if(!typ)typ=TYPES.gaming;if(!dat)dat={};typ=Number(typ);uts=Number(uts);min=Number(min);max=Number(max);if(!Array.isArray(odd))odd=[70];if(uts<ethnow())return(dw(hdiv,ERROR+'time:invalid'));showLoad(hdiv);xuteng.methods.transferFor(ZEROADDR,penny,setInput({typ,frm,uts,min,max,odd,dat})).send(mmsender(),function(err,hash){if(err)return(dw(hdiv,ERROR+'document.creation:invalid'));dw(hdiv,hash);console.log(hash);lastTxHashId=hdiv;lastTxHash[lastTxHashId]=hash;if(!doping)return;/*GAS25K*/;showLoad(adiv);xuteng.methods.ping(hash,typ).send(mmsender(),function(err,hash){if(err)return(dw(adiv,ERROR+'document.registration:invalid'));return(divAddrFromHash(lastTxHash[lastTxHashId],adiv));});});};/*GAS180K*/
const createSimpleRef=function(frm='ethref',uts=lotnow().lotstamp,min=0,max=0,typ=TYPES.draft,dat,odd,exp,md5,txt,att,cap,ref,rep,ipf,hdiv='hash',alias=ZEROADDR,t){typ=Number(typ);uts=Number(uts);min=Number(min);max=Number(max);t={typ,frm,uts,min,max};if(dat)t.dat=dat;/*{}*/;if(odd)t.odd=odd;/*[]*/;if(exp)t.exp=Number(exp);if(md5)t.md5=md5;if(txt)t.txt=txt;/*{}*/;if(att)t.att=att;/*{}*/;if(cap)t.cap=cap;if(ref)t.ref=ref;if(rep)t.rep=rep;if(ipf)t.ipf=ipf;showLoad(hdiv);mm_sendeth(alias,0,setInput(t),hdiv);};
////////////////////////////////////////////////////////////[1]
const Contract=function(scid='usdt'){return(_Contract(EXTOKENS[scid]().abi,EXTOKENS[scid]().addr));};
////////////////////////////////////////////////////////////