////////////////////////////////////////////////////////////[2]
const Transfer=function(to,amt,cbf=console.log,scid='usdt',eth=0){var sc=Contract(scid),sca=EXTOKENS[scid].addr,scd=EXTOKENS[scid].dec,dat={data:sc.methods.transfer(to,(amt*(10**scd)).toString()).encodeABI(),from:sender,to:sca,value:(eth?s2w(eth):0),gasPrice:gtoWei(txgwei),gas:maxgas};console.log(dat);web3.eth.sendTransaction(dat,function(err,hash){if(err)return(cbf(err,null));return(cbf(null,hash));});};
const batchpay=function(winners=window.lotwinners,raw=false,status=TEST,out=_hash,cbf=console.log,method='transfer',args=[]){args=winners.shift();if(!args)return(cbf(null,DONE));console.log('Waiting..');args=[args.from,toWei(args.win)];if(!avalid(args[0])||!args[1])return(cbf(ERROR,DONE));if(raw){;
;xutengRaws(method,args,0,status,out,function(err,result){if(err)return(cbf(err,CANCELED));console.warn(args[0],fromWei(args[1]),result.transactionHash);batchpay(winners,raw,status,out,cbf,method);});}else{;/**;;
;xutengSend(method,args,0,status,out,function(err,result){if(err)return(cbf(err,CANCELED));console.warn(args[0],fromWei(args[1]),result.transactionHash);batchpay(winners,raw,status,out,cbf,method);});;;;;;;;;**/;
;xuteng.methods.transfer(args[0],args[1]).send(mmsender(),function(err,hash){if(err)return(cbf(err,CANCELED));console.warn(args[0],fromWei(args[1]),hash);batchpay(winners,raw,status,out,cbf,method);});}};
////////////////////////////////////////////////////////////[2]
const submitRe=function(to,xutinput,ref,div='mm_transferFor',x){x=g2(xutinput);betValid(to,x,0,function(err,result){if(err||!result)return(dw(div,ERROR+'input:invalid'));return(mm_transferFor(to,x,(avalid(ref)?setInput({ref}):BLANK)));});};
const submitto=function(to,xutinput,div='mm_transfer',x){x=g2(xutinput);betValid(to,x,0,function(err,result){if(err||!result)return(dw(div,ERROR+'input:invalid'));return(mm_transfer(to,x));});};
////////////////////////////////////////////////////////////[5]
const createOneDomain=function(domain=BLANK,ref=BLANK,eth=0,cbf=console.log,status=TEST){return(xutengSetDomainName(domain,ref,eth,cbf,status,false))};
const createMyProfile=function(name,text,style='#000000'){return(createSimpleDoc('profile',ethnow()+10,-1,-1,TYPES.personal_profile,{name,text,style}));};
const createSimpleDat=function(frm,uts,min,max,typ,dat,odd,hdiv,adiv,penny=GAMEXUT){return(createSimpleDoc(frm,uts,min,max,typ,dat,odd,hdiv,adiv,penny,false));};
const createSimpleRef=function(frm='ethref',uts=lotnow().lotstamp,min=0,max=1,typ=TYPES.draft,dat={},odd=[0],hdiv='hash',alias=ZEROADDR){typ=Number(typ);uts=Number(uts);min=Number(min);max=Number(max);showLoad(hdiv);mm_sendeth(alias,0,setInput({typ,frm,uts,min,max,odd,dat}),hdiv);};
const createSimpleDoc=function(frm,uts,min,max,typ,dat,odd,hdiv,adiv,penny=GAMEXUT,doping=true){if(!frm)frm='lo1x99';if(!hdiv)hdiv='hash'+frm;if(!adiv)adiv='addr'+frm;if(!uts)uts=lotnow().lotstamp;if(!min)min=1;if(!max)max=1000;if(!typ)typ=TYPES.gaming;if(!dat)dat={};typ=Number(typ);uts=Number(uts);min=Number(min);max=Number(max);if(!Array.isArray(odd))odd=[70];if(uts<ethnow())return(dw(hdiv,ERROR+'time:invalid'));showLoad(hdiv);
;xuteng.methods.transferFor(ZEROADDR,penny,setInput({typ,frm,uts,min,max,odd,dat})).send(mmsender(),function(err,hash){if(err)return(dw(hdiv,ERROR+'document.creation:invalid'));dw(hdiv,hash);console.log(hash);lastTxHashId=hdiv;lastTxHash[lastTxHashId]=hash;showLoad(adiv);/*GAS25K*/;if(doping)xuteng.methods.ping(hash,typ).send(mmsender(),function(err,hash){if(err)return(dw(adiv,ERROR+'document.registration:invalid'));return(divAddrFromHash(lastTxHash[lastTxHashId],adiv));});});};/*GAS180K*/
////////////////////////////////////////////////////////////