////////////////////////////////////////////////////////////[3]
const setPGwei=function(){gasPGwei((e,gwei)=>{if(e)return;console.log('GWEI:',gwei);try{document.getElementById(_txgwei).options[0]=(new Option('GWEI:'+gwei,gwei));}catch(e){}});};
const gasPGwei=function(cbf){web3.eth.getGasPrice().then((resolve,reject)=>{if(reject)return(cbf(reject,null));window.txgwei=gfromWei(resolve);return(cbf(null,window.txgwei));});};
const betValid=function(to,xut,uts,cbf){txaddr(to,function(err,result){if(err)return(cbf(err,null));if(!result)return(cbf(null,undefined));if(!uts)uts=ethnow();if(xut<result.min||xut>result.max)return(cbf(null,0));if(uts<result.txUts||uts>result.uts)return(cbf(null,false));return(cbf(null,result.txBlock));});};
////////////////////////////////////////////////////////////[3]
const txaddr=function(txa,cbf,idx=0){xuteng.methods.hashesOf(txa,idx).call((err,result)=>{if(err)return(cbf(err,null));dehash(result,function(err,result){if(err)return(cbf(err,null));cbf(null,result);});});};
const deaddr=function(uaw,cbf,idx=0){xuteng.methods.typedContentsOf(uaw,TYPES.personal_profile,idx).call((err,result)=>{if(err)return(cbf(err,null));xuteng.methods.hashesOf(result,0).call((err,result)=>{if(err)return(cbf(err,null));dehash(result,function(err,result){if(err)return(cbf(err,null));cbf(null,result);});});});};
const dehash=function(txh,cbf){web3.eth.getTransaction(txh,function(err,result){if(err)return(cbf(err,null));console.log(result.input);txh=hexObj(result.input);if(!txh.obj)txh={obj:{raw:result.input}};Object.assign(txh.obj,{txBlock:Number(result.blockNumber),txAuthor:result.from,txWei:result.value});web3.eth.getBlock(result.blockNumber).then(result=>{txh.obj.txUts=result.timestamp;cbf(null,txh.obj);}).catch(err=>{txh.obj.txUts=0;cbf(null,txh.obj);});});};//#forms.getInput();
////////////////////////////////////////////////////////////[2]
const lotter=async(timestamp,digits,maxdig,cbf)=>{if(timestamp>lotnow().lotstamp)return(cbf(null,[-4]));if(!timestamp)timestamp=lotnow().lotstamp;if(!digits)digits=1;if(!maxdig)maxdig=99;window.lotstamp=Number(timestamp);window.lotdigits=Number(digits);window.lotmaxdig=Number(maxdig);window.blocknum=0;await(getBStop(0,window.lotstamp));if(!window.blocknum)return(cbf(null,[-1]));getlot(window.blocknum,cbf);};//GenerateWinningNumbers;
const getlot=function(block,cbf,skip=0,maxpage=99,i){if(window.lotdigits>7)return(cbf(null,[-3]));if(!skip)window.eventpicks=[];xuteng.getPastEvents('Transfer',{fromBlock:block-999,toBlock:block},function(err,result){if(err)return(cbf(err,null));if(skip>maxpage)return(cbf(null,[-2]));if(!result||!result.length)return(getlot(block-999-1,cbf,++skip));for(i=result.length-1;result[i]&&window.eventpicks.length<10;i--){window.eventpicks.push(result[i]);}if(window.eventpicks.length<10)return(getlot(block-999-1,cbf,++skip));
;window.numberpicks=[];window.cryptstring=window.lotstamp+COLON+window.blocknum+COLON;for(i=window.eventpicks.length-1;i>0;i--){window.cryptstring+=toHash(window.eventpicks[i].blockHash+window.eventpicks[i].blockNumber+window.eventpicks[i].transactionHash+window.eventpicks[i].transactionIndex+window.eventpicks[i].signature);};console.log(window.cryptstring);while(window.numberpicks.length<window.lotdigits){window.cryptstring=toHash(window.cryptstring+HYPHEN+window.lotdigits+COLON+window.lotmaxdig);window.lottonum=h2m(window.cryptstring.slice(2),window.lotmaxdig);if(window.numberpicks.includes(window.lottonum))continue;window.numberpicks.push(window.lottonum);}return(cbf(null,window.numberpicks));});};
////////////////////////////////////////////////////////////[4]
const logBStop=async(timestamp)=>{await(getBStop(0,timestamp));console.log('StopBlock:'+window.blocknum);}
const getBLast=async()=>{window.blocknum=await(web3.eth.getBlockNumber());console.log('Latest:'+window.blocknum);};
const getBTime=async(block)=>{block=await(web3.eth.getBlock(block));if(!block){console.log('BlockNotFound');return;}window.blockstamp=block.timestamp;console.log('BlockStamp:'+window.blockstamp);console.log('BlockTime:'+fromDate(window.blockstamp));};
const getBStop=async(skip,timestamp,block)=>{if(!skip){await(getBLast());skip=Number(window.blocknum);}if(timestamp)window.lotstamp=Number(timestamp);block=await(web3.eth.getBlock(window.blocknum));if(!block){console.log('BlockNotFound');return;}if(block.timestamp==window.lotstamp)return;if(skip==0&&ethnow()<window.lotstamp)return;if(skip==1&&block.timestamp>window.lotstamp)return;if(skip==1&&block.timestamp<window.lotstamp)return(++window.blocknum);skip=Math.ceil(skip/2);if(block.timestamp>window.lotstamp){window.blocknum-=skip;}else{window.blocknum+=skip;}return(getBStop(skip));};//GetClosestStopBlock;
////////////////////////////////////////////////////////////[5]
/// window.lotsubmits;window.numsubmits;window.numresults;window.blocknum;window.lotodds;
/// window.lotaddress;window.lotauthor;window.lotblock;window.lotstamp;window.xutminip;window.xutmaxip;
const reTransferTx=function(txh,cbf,o,d){web3.eth.getTransaction(txh,function(err,result){if(err)return(cbf(err,null));o={from:result.from,contact:result.to,hexdata:result.input,block:result.blockNumber,gas:result.gas,eth:fromWei(result.value)};d=dedata(o.hexdata);if(d){o.xutrec=d.data[0];o.xutval=fromWei(d.data[1]);o.xutdoc=d.data[2];o.func=d.func;}return(cbf(null,o));});};
const scanTxLottos=async(ga,cbf)=>{window.lotaddress=ga;txaddr(ga,function(err,result){if(err)return(cbf(err,null));if(!result||!result.txBlock||!result.uts)return(cbf(null,undefined));window.lotauthor=result.txAuthor;window.lotblock=result.txBlock;window.lotstamp=result.uts;window.xutminip=result.min;window.xutmaxip=result.max;window.lotodds=result.odd;web3.eth.getBlockNumber().then(result=>{window.blocknum=result;console.log('StartBlock:'+window.lotblock);console.log('StopTime:'+window.lotstamp);if(ethnow()>window.lotstamp)await(getBStop(0,window.lotstamp));console.log('StopBlock:'+window.blocknum);scanTxEvents(window.lotaddress,window.lotblock,window.blocknum,window.xutminip,window.xutmaxip,cbf);}).catch(err=>{return(cbf(err,null));});});};
const scanTxEvents=function(ga,bfrom,bto,xmin,xmax,cbf,i,n){window.lotsubmits=[];xuteng.getPastEvents('Transfer',{filter:{toAddress:ga},fromBlock:bfrom,toBlock:bto},function(err,result){if(err)return(cbf(err,null));for(i=0;i<result.length;i++){n=fromWei(result[i].returnValues.txPenny);if(xmin<=n&&n<=xmax)window.lotsubmits.push({from:result[i].returnValues.fromAddress,xut:n,tx:result[i].transactionHash});}}).then(function(result){for(i=0;i<result.length;i++){console.log(result[i].returnValues.fromAddress,COLON,result[i].returnValues.txPenny);};return(cbf(null,window.lotsubmits));});};
const lo1x99submit=function(desubmits,cbf,i,j,k,x){submits=Object.assign([],desubmits);for(i=0;i<100;i++){if(i==0)window.numsubmits={};window.numsubmits[i]=[];}if(!submits||!submits.length)return(cbf(null,window.numsubmits));for(i=0;i<100;i++){for(j=0;j<submits.length;j++){if(submits[j]&&submits[j].from&&submits[j].xut){x=xut2de(submits[j].xut);for(k=0;k<x.de.length;k++){if(Number(x.de[k])==i){window.numsubmits[i].push({from:submits[j].from,xut:x.xut,tx:submits[j].tx});}}}}}return(cbf(null,window.numsubmits));};//desubmits[]<=>window.lotsubmits[];//ArrayObjectFrom[scanTxEvents()];
const lo1x99winner=function(detable,win,mul,cbf,i){table=Object.assign({},detable);if(!mul)mul=70;if(table[win]&&table[win].length){for(i=0;i<table[win].length;i++){table[win][i].win=mul*table[win][i].xut};return(cbf(null,{wins:table[win]}));}return(cbf(ERROR,null));};//detable{}<=>window.numsubmits{};//CleanObjectFrom[lo1x99submit()];
////////////////////////////////////////////////////////////[2]
const loNxNNresult=function(desubmits,wins,cbf,i,j){if(!wins.length||wins.length<2)return(cbf(ERROR,null));submits=Object.assign([],desubmits);for(i=1;i<=wins.length;i++){if(i==1)window.numresults={};window.numresults[i]=[];}if(!submits||!submits.length)return(cbf(null,window.numresults));for(i=1;i<=wins.length;i++){for(j=0;j<submits.length;j++){if(submits[j]&&submits[j].from&&submits[j].xut){if(reLottoArray(wins,xut2lo(submits[j].xut).lo)==i)window.numresults[i].push({from:submits[j].from,xut:submits[j].xut,tx:submits[j].tx,lotto:i});}}}return(cbf(null,window.numresults));};//desubmits[]<=>window.lotsubmits[];
const loNxNNwinner=function(detable,winobj,cbf,i){table=Object.assign({},detable);Object.keys(winobj).forEach(function(key){if(table[key]&&table[key].length){for(i=0;i<table[key].length;i++){if(table[key][i].lotto==key&&Number(winobj[key])>0)table[key][i].win=winobj[key]*table[key][i].xut;}}});return(cbf(null,{wins:table}));};//detable{}<=>window.numresults{};//winobj{}={1:N,2:NN,,,7:NNN};
////////////////////////////////////////////////////////////[6]
const getAddrFromHash=function(h,cbf){xuteng.methods.addressOf(h).call((err,result)=>{cbf(err,result);});};
const divAddrFromHash=function(h,div){getAddrFromHash(h,function(err,result){if(err)return(dw(div,ERROR));dw(div,result);});};
const dehashLottoGame=function(h,div,cbf){dehash(h,function(err,result){if(err)return(dw(div,ERROR));if(cbf)return(cbf(null,result));window.txforDocDat=result;dwMyGameProfile(div,result);});};
const deaddrLottoGame=function(a,div,cbf){txaddr(a,function(err,result){if(err)return(dw(div,ERROR));if(cbf)return(cbf(null,result));window.txforDocDat=result;dwMyGameProfile(div,result);});};
const dehashMyProfile=function(h,div,cbf){dehash(h,function(err,result){if(err)return(dw(div,ERROR));if(cbf)return(cbf(null,result));window.txforDocDat=result;dwMyAddrProfile(div,result);});};
const deaddrMyProfile=function(a,div,cbf){deaddr(a,function(err,result){if(err)return(dw(div,ERROR));if(cbf)return(cbf(null,result));window.txforDocDat=result;dwMyAddrProfile(div,result);});};
////////////////////////////////////////////////////////////