////////////////////////////////////////////////////////////
const LABELS={en:{
_button_AuthAccExp: "EXPORT PRIVATE KEY",
_button_AuthAccImp: "IMPORT PRIVATE KEY",
_button_AuthAccNew: "CREATE NEW",
_button_AuthCokDel: "DEL COOKIE/",
_button_AuthCokGet: "GET COOKIE/",
_button_AuthCokSet: "SET COOKIE/",
_button_AuthCpyExp: "COPY THIS KEY",
_button_AuthCpyKey: "COPY THIS KEY",
_button_AuthCpyKst: "COPY THIS/",
_button_AuthCpySig: "COPY THIS SIGNATURE",
_button_AuthKstDec: "UNLOCK",
_button_AuthPayEth: "SEND ETH",
_button_AuthPayXut: "SEND XUT",
_button_AuthSigSig: "SIGN",
_button_AuthSigVer: "VERIFY",
_button_BuyOfr: "BUY NOW",
_button_DisBuy: "STOP THIS REQUEST",
_button_DisSel: "STOP THIS OFFER",
_button_EthXut: "BUY NOW",
_button_GetBuy: "BUYING REQUEST#",
_button_GetOfr: "SELLER OFFER#",
_button_GetReq: "BUYER REQUEST#",
_button_GetSel: "SELLING OFFER#",
_button_GoUser: "USER ADDRESS",
_button_SelReq: "SELL NOW",
_button_SetBuy: "POST THIS REQUEST",
_button_SetFee: "SET MEMBER FEE",
_button_SetSel: "POST THIS OFFER",
_button_SysReg: "PAY TO REGISTER",
_button_XutXut: "SELL NOW",
_header_account: "CREATE NEW OR IMPORT EXISTING PRIVATE KEY",
_header_allow: "XUTENG TOKEN TRANSFER PERMISSION",
_header_buy: "DIRECTLY BUY XUTENG TOKENS FROM SYSTEM FUND",
_header_buyfrom: "BUY XUTENG TOKENS FROM ANOTHER USER",
_header_buying: "REVIEW BUYING REQUEST",
_header_copyright: "(C)2019 ASINERUM INTERNATIONAL PROJECT",
_header_cost: "ETHEREUM TRANSACTION COST",
_header_keystore: "SELECT NETWORK AND UNLOCK YOUR KEYSTORE",
_header_rate: "XUTENG TOKEN OFFICIAL EXCHANGE RATE",
_header_register: "REGISTER AS A LEVELED USER",
_header_sell: "DIRECTLY SELL XUTENG TOKENS TO SYSTEM FUND",
_header_selling: "REVIEW SELLING OFFER",
_header_sellto: "SELL XUTENG TOKENS TO ANOTHER USER",
_header_sender: "PERSONAL INFORMATION AND STATS",
_header_sendeth: "PERSONAL ETHEREUM BALANCE",
_header_sign: "SIGN AND VERIFY TEXT MESSAGE",
_header_stats: "XUTENG TOKEN MARKETPLACE STATS",
_header_system: "XUTENG TOKEN SYSTEM OVERVIEW",
_header_tobuy: "REQUEST TO BUY XUTENG TOKENS",
_header_tosell: "OFFER TO SELL XUTENG TOKENS",
_header_transfer: "PERSONAL XUTENG BALANCE",
_header_user: "ANOTHER USER INFORMATION AND STATS",
_label_AllowToBuy: "USER CAN BUY",
_label_AllowToSel: "USER CAN SELL",
_label_AllowToTrs: "USER TRANSFER",
_label_AllowToTrx: "USER EXCHANGE",
_label_AuthAccKey: "NEW PRIVATE KEY",
_label_AuthGasMax: "GAS LIMIT",
_label_AuthGasWei: "GAS PRICE",
_label_AuthKstNet: "NETWORK",
_label_AuthKstPwd: "PASSWORD",
_label_AuthKstRpc: "RPC SERVER",
_label_AuthKstore: "KEYSTORE",
_label_AuthSigMsg: "MESSAGE",
_label_AuthSigUsr: "SIGNATORY ADDRESS",
_label_AuthSumEth: "ETH BALANCE",
_label_AuthSumXut: "XUT BALANCE",
_label_Buying0Xut: "YOUR XUT BALANCE",
_label_Buying1Eth: "YOUR ETH BALANCE",
_label_Buying2Adr: "SELLER ADDRESS",
_label_Buying4Tpe: "EXCHANGE RATE",
_label_Buying5Dep: "SELLER DEPOSIT",
_label_Buying6Num: "SYSTEM COUNT",
_label_Buying7Get: "XUT TO BUY",
_label_Buying8Pay: "ETH TO PAY",
_label_Counts0Buy: "REQUESTS TO BUY",
_label_Counts1Sel: "OFFERS TO SELL",
_label_Ofrsel0Xut: "YOUR XUT BALANCE",
_label_Ofrsel1Eth: "YOUR ETH BALANCE",
_label_Ofrsel1Tpe: "EXCHANGE RATE",
_label_Ofrsel2Cnt: "POSTED OFFERS",
_label_Ofrsel2Dep: "XUT DEPOSITED",
_label_Ofrsel3Fee: "POSTING FEE",
_label_Ofrsel4Ask: "EXPECTED RATE",
_label_Ofrsel5Pay: "XUT TO DEPOSIT",
_label_Ofrsel6Rec: "ETH TO RECEIVE",
_label_Reqbuy0Xut: "YOUR XUT BALANCE",
_label_Reqbuy1Eth: "YOUR ETH BALANCE",
_label_Reqbuy1Tpe: "EXCHANGE RATE",
_label_Reqbuy2Cnt: "POSTED REQUESTS",
_label_Reqbuy2Dep: "ETH DEPOSITED",
_label_Reqbuy3Fee: "POSTING FEE",
_label_Reqbuy4Ask: "EXPECTED RATE",
_label_Reqbuy5Rec: "XUT TO RECEIVE",
_label_Reqbuy6Pay: "ETH TO DEPOSIT",
_label_Seling0Xut: "YOUR XUT BALANCE",
_label_Seling1Eth: "YOUR ETH BALANCE",
_label_Seling2Adr: "BUYER ADDRESS",
_label_Seling4Tpe: "EXCHANGE RATE",
_label_Seling5Dep: "BUYER DEPOSIT",
_label_Seling6Num: "SYSTEM COUNT",
_label_Seling7Pay: "XUT TO SELL",
_label_Seling8Get: "ETH TO GET",
_label_Sender0Buy: "REQUESTS TO BUY",
_label_Sender1Sel: "OFFERS TO SELL",
_label_Sender2Msg: "MESSAGES",
_label_Sender3Rol: "ROLE",
_label_Sender4Rnk: "RANK",
_label_Sender5Lvl: "LEVEL",
_label_Sender6Mem: "MEMBERS",
_label_Sender7Fee: "MEMBER FEE",
_label_Sys0TpeSel: "SELLING RATE",
_label_Sys1TpeBuy: "BUYING RATE",
_label_Sysbuy0Xut: "YOUR XUT BALANCE",
_label_Sysbuy1Eth: "YOUR ETH BALANCE",
_label_Sysbuy2Tpe: "EXCHANGE RATE",
_label_Sysbuy3Max: "XUT MAX BUY",
_label_Sysbuy4Get: "XUT TO BUY",
_label_Sysbuy5Pay: "ETH TO PAY",
_label_Sysreg0Xut: "YOUR XUT BALANCE",
_label_Sysreg1Eth: "YOUR ETH BALANCE",
_label_Sysreg2Lvl: "YOUR CURRENT LEVEL",
_label_Sysreg3Exp: "EXPIRATION TIME",
_label_Sysreg4Fee: "REGISTER FEE",
_label_Sysreg5Amt: "REGISTER AMOUNT",
_label_Syssel0Xut: "YOUR XUT BALANCE",
_label_Syssel1Eth: "YOUR ETH BALANCE",
_label_Syssel2Tpe: "EXCHANGE RATE",
_label_Syssel3Max: "ETH PAY FUND",
_label_Syssel4Pay: "XUT TO SELL",
_label_Syssel5Get: "ETH TO GET",
_label_Tok0IdName: "NAME",
_label_Tok1Symbol: "SYMBOL",
_label_Tok2Supply: "TOTAL SUPPLY",
_label_Tok3SysXut: "TOKENS FOR SALE",
_label_Tok4SysEth: "ETHEREUM BALANCE",
_label_Wallet1Xut: "XUT BALANCE",
_label_Wallet2Eth: "ETH BALANCE",
_label_Wallet3Req: "REQUESTS TO BUY",
_label_Wallet4Ofr: "OFFERS TO SELL",
_label_Wallet5Rol: "ROLE",
_label_Wallet6Rnk: "RANK",
_label_Wallet7Lvl: "LEVEL",
_label_Wallet8Mem: "MEMBERS",
_label_Wallet9Fee: "MEMBER FEE",
_note_BuyOfr: "EXCLUDING GAS FEE",
_note_DisBuy: "EXCLUDING GAS FEE",
_note_DisSel: "EXCLUDING GAS FEE",
_note_EthXut: "EXCLUDING GAS FEE",
_note_SelReq: "EXCLUDING GAS FEE",
_note_SetBuy: "EXCLUDING GAS FEE",
_note_SetSel: "EXCLUDING GAS FEE",
_note_SysReg: "EXCLUDING GAS FEE",
_note_XutXut: "EXCLUDING GAS FEE",
}}//////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////