////////////////////////////////////////////////////////////
const nolink='<i\tclass="fa\u0020fa-trash"></i>';
const xgaUrl='https://game.asinerum.workers.dev/#a=';
const xgtUrl='https://paix.asinerum.workers.dev/#a=';/*hash*/
const btnXut=function(tag,nid,a,n,i,t){if(!nid)nid='xut-';a={};n=document.getElementsByTagName(tag?tag:STAR);for(i=0;i<n.length;i++){t=n[i].className;if(t&&t.indexOf(nid)===0){a[t]={index:i,address:t.split(HYPHEN)[1],value:n[i].getAttribute('value'),fixed:n[i].getAttribute('fixed'),size:n[i].getAttribute('size'),ref:n[i].getAttribute('ref')};console.log(a[t]);}};
;if(nid=='xut-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address))xuteng.methods.incomeOf(a[t].address).call(function(err,result){if(err){mw(t,nolink);}else{mw(t,'<button\tclass="axut\u0020bxut"\tonclick="incomeOf(\''+a[t].address+'\',\'of-'+a[t].address+'\');"><i\tclass="fa\u0020fa-flask"></i></button><button\tclass="axut"><span\tclass="of-'+a[t].address+'">'+w2s(result)+'</span></button><button\tclass="axut\u0020bxut"\tonclick="mm_transfer(\''+a[t].address+'\',g2(\''+a[t].index+HYPHEN+a[t].address+'\'));"><i\tclass="fa\u0020fa-diamond"></i></button><input\ttype="text"\tclass="axut\u0020bxut"\tid="'+a[t].index+HYPHEN+a[t].address+'"\tsize="'+(a[t].size?a[t].size:5)+'"\tvalue="'+(a[t].value?Number(a[t].value):1)+'"'+(a[t].fixed?'\tdisabled':'')+'/>');}});/**RPC**/;});/**keys**/;
;if(nid=='eth-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address)){window.ethref=setInput({ref:a[t].ref});mw(t,'<button\tclass="axut\u0020bxut"\tonclick="mm_sendeth(\''+a[t].address+'\','+a[t].value+',window.ethref,\''+a[t].index+HYPHEN+a[t].address+'\');"\tid="'+a[t].index+HYPHEN+a[t].address+'">ETH&nbsp;'+a[t].value+'</button>');}});/**keys**/;
;if(nid=='xga-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address))deaddrLottoGame(a[t].address,TEST,function(err,result){if(err||!result||!result.dat||!result.dat.name){mw(t,nolink);}else{mw(t,'<button\tclass="axut\u0020bxut"\tonclick="window.open(\''+xgaUrl+a[t].address+'\');">'+result.dat.name+'</button>');}});/**RPC**/;});/**keys**/;
;if(nid=='xgt-')Object.keys(a).forEach(function(t){if(a[t]&&hvalid(a[t].address))dehashLottoGame(a[t].address,TEST,function(err,result){if(err||!result||!result.dat||!result.dat.name){mw(t,nolink);}else{mw(t,'<button\tclass="axut\u0020bxut"\tonclick="window.open(\''+xgtUrl+a[t].address+'\');">'+result.dat.name+'</button>');}});/**RPC**/;});/**keys**/;
;if(nid=='xtx-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address))mw(t,'<button\tclass="axut\u0020bxut"\tonclick="mm_transfer(\''+a[t].address+'\','+a[t].value+',\''+a[t].index+HYPHEN+a[t].address+'\');"\tid="'+a[t].index+HYPHEN+a[t].address+'">XUT&nbsp;'+a[t].value+'</button>');});/**keys**/;
;if(nid=='xxx-')Object.keys(a).forEach(function(t){;;;});/**keys**/;};
////////////////////////////////////////////////////////////
const cmtXut=function(str,a,b,i){a=str.match(/\[xut\](.*?)\[\/xut\]/g);b=str.match(/\[xut=(.*?)\]/g);if(a)for(i=0;i<a.length;i++){str=str.replace(a[i],'<b\u0020class="xut-'+a[i].replace(/\[\/?xut\]/g,'')+'"></b>');};if(b)for(i=0;i<b.length;i++){str=str.replace(b[i],'<b\u0020class="xut-'+b[i].slice(5).split(']')[0]+'"></b>');};return(str);};
const launch=function(mg=200000,gw=0){startXuteng();maxgas=mg;txgwei=gw;btnXut('b','xut-');btnXut('b','eth-');btnXut('b','xga-');btnXut('b','xgt-');btnXut('b','xtx-');};
const xready=function(mg=200000,gw=0){$(document).ready(function(){launch(mg,gw);});};
////////////////////////////////////////////////////////////