////////////////////////////////////////////////////////////
const nolink='<i\u0020class="fa\u0020fa-trash"></i>';
const xgaUrl='https://game.asinerum.workers.dev/#a=';/*addr*/
const xgtUrl='https://epay.asinerum.workers.dev/#a=';/*hash*/
const btnXut=function(tag,nid,a,n,i,t){if(!nid)nid='xut-';a={};n=document.getElementsByTagName(tag?tag:STAR);for(i=0;i<n.length;i++){t=n[i].className;if(t&&t.indexOf(nid)===0){a[t]={index:i,address:t.split(HYPHEN)[1],value:n[i].getAttribute('value'),fixed:n[i].getAttribute('fixed'),size:n[i].getAttribute('size'),ref:n[i].getAttribute('ref')};console.log(a[t]);}};if(!window.ethref)window.ethref={};
;if(nid=='xut-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address)){xuteng.methods.incomeOf(a[t].address).call(function(err,result){if(err){mw(t,nolink);}else{mw(t,'<button\u0020class="axut\u0020bxut"\u0020onclick="incomeOf(\''+a[t].address+'\',\'of-'+a[t].address+'\');"><i\u0020class="fa\u0020fa-flask"></i></button><button\u0020class="axut"><span\u0020class="of-'+a[t].address+'">'+w2s(result)+'</span></button><button\u0020class="axut\u0020bxut"\u0020onclick="mm_transfer(\''+a[t].address+'\',g2(\''+a[t].index+HYPHEN+t+'\'));"><i\u0020class="fa\u0020fa-diamond"></i></button><input\u0020type="text"\u0020class="axut\u0020bxut"\u0020id="'+a[t].index+HYPHEN+t+'"\u0020size="'+(a[t].size?a[t].size:5)+'"\u0020value="'+(a[t].value?Number(a[t].value):1)+'"'+(a[t].fixed?'\u0020disabled':'')+'/>');}});/**RPC**/;}});/**keys**/;
;if(nid=='etx-')Object.keys(a).forEach(function(t){if(a[t]&&hvalid(a[t].address)){dehashLottoGame(a[t].address,TEST,function(err,result){i=lotnow().lotstamp;n=a[t].value?a[t].value:(result.max?result.max:0);window.ethref[a[t].index+HYPHEN+t]=setInput({ref:a[t].address});if(err||!result||!result.txAuthor||(result.exp&&result.exp<i)||([TYPES.betting,TYPES.bid_buying,TYPES.bid_selling,TYPES.gambling,TYPES.gaming].includes(result.typ)&&result.uts<i)){mw(t,nolink);}else{mw(t,'<button\u0020class="axut\u0020bxut"\u0020onclick="mm_sendeth(\''+result.txAuthor+'\','+n+',window.ethref[\''+a[t].index+HYPHEN+t+'\'],\''+a[t].index+HYPHEN+t+'\');"\u0020id="'+a[t].index+HYPHEN+t+'">ETH&nbsp;'+n+'</button>');}});/**RPC**/;}});/**keys**/;
;if(nid=='eth-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address)){window.ethref[a[t].index+HYPHEN+t]=setInput({ref:a[t].ref});mw(t,'<button\u0020class="axut\u0020bxut"\u0020onclick="mm_sendeth(\''+a[t].address+'\','+a[t].value+',window.ethref[\''+a[t].index+HYPHEN+t+'\'],\''+a[t].index+HYPHEN+t+'\');"\u0020id="'+a[t].index+HYPHEN+t+'">ETH&nbsp;'+a[t].value+'</button>');}});/**keys**/;
;if(nid=='xga-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address)){deaddrLottoGame(a[t].address,TEST,function(err,result){if(err||!result||!result.dat||!result.dat.name){mw(t,nolink);}else{mw(t,'<button\u0020class="axut\u0020bxut"\u0020onclick="window.open(\''+xgaUrl+a[t].address+'\');">'+result.dat.name+'</button>');}});/**RPC**/;}});/**keys**/;
;if(nid=='xgt-')Object.keys(a).forEach(function(t){if(a[t]&&hvalid(a[t].address)){dehashLottoGame(a[t].address,TEST,function(err,result){if(err||!result||!result.dat||!result.dat.name){mw(t,nolink);}else{mw(t,'<button\u0020class="axut\u0020bxut"\u0020onclick="window.open(\''+xgtUrl+a[t].address+'\');">'+result.dat.name+'</button>');}});/**RPC**/;}});/**keys**/;
;if(nid=='xtx-')Object.keys(a).forEach(function(t){if(a[t]&&avalid(a[t].address)){mw(t,'<button\u0020class="axut\u0020bxut"\u0020onclick="mm_transfer(\''+a[t].address+'\','+a[t].value+',\''+a[t].index+HYPHEN+t+'\');"\u0020id="'+a[t].index+HYPHEN+t+'">XUT&nbsp;'+a[t].value+'</button>');}});/**keys**/;
;if(nid=='xxx-')Object.keys(a).forEach(function(t){;;;});/**keys**/;};
////////////////////////////////////////////////////////////
const cmtXut=function(str,a,b,i){a=str.match(/\[xut\](.*?)\[\/xut\]/g);b=str.match(/\[xut=(.*?)\]/g);if(a)for(i=0;i<a.length;i++){str=str.replace(a[i],'<b\u0020class="xut-'+a[i].replace(/\[\/?xut\]/g,'')+'"></b>');};if(b)for(i=0;i<b.length;i++){str=str.replace(b[i],'<b\u0020class="xut-'+b[i].slice(5).split(']')[0]+'"></b>');};return(str);};
const launch=function(mg=200000,gw=0){startXuteng();maxgas=mg;txgwei=gw;btnXut('b','xut-');btnXut('b','etx-');btnXut('b','eth-');btnXut('b','xga-');btnXut('b','xgt-');btnXut('b','xtx-');};
const xready=function(mg=200000,gw=0){$(document).ready(function(){launch(mg,gw);});};
////////////////////////////////////////////////////////////
const nonce=async(pops=3,cbf=null,b,k,i,m)=>{await(xutengFemt.methods.basicRate().call().then(r=>{b=r}));await(xutengFemt.methods.randomKey().call().then(r=>{k=r}));m=big(k).mod(big(b)).toString();for(i=1;i<b*pops;i++){if(m==big(b2i(kec(k,i))).mod(big(b)).toString()){console.log(FOUND,i);break;}};if(i>=b*pops){console.log(UNCHECKED)}};
const Femt=async(pops=3)=>{await(initFemt());nonce(pops);};
const Gemt=async(pops=3)=>{await(initGemt());nonce(pops);};
const Nemt=async(pops=3)=>{await(initNemt());nonce(pops);};
////////////////////////////////////////////////////////////